<div id="<?= $this->id ?>" class="<?= $this->class ?> animated fadeInRight" <?= $this->customAttr ?>>
    <?php if ($this->title != '') { ?>
        <div class="title"><div class="row"><div class="col s12"><?= $this->title ?></div></div></div>
            <?php } ?>
            <?php foreach ($this->getElements() as $obj) { ?>
                <?php echo $obj->getHtml() ?>
            <?php } ?>
</div>