<span class="<?php echo $this->wrapper_class ?>" data-on-document-ready="">
    <label>
        <input class="<?php echo $this->class ?>" type="checkbox" name="<?php echo $this->name ?>" <?php echo $this->customAttr ?> <?php echo ($this->checked ? ' checked="checked"' : '') ?>>
        <span></span>
    </label>
    <label class="active label">
        <?php foreach ($this->getElements() as $obj) { ?>
            <?php echo $obj->getHtml(); ?>
        <?php } ?>
        <?php echo ($this->required == true ? ' *' : '') ?>
    </label>
</span>