<div class="page-overlay">
    <div id="datePickerWrapper" class="<?= $this->class ?>"  <?= $this->customAttr ?>
         data-on-document-changed="initDatumInputEvent">
        <div class="date-picker-wrapper">
            <div class="date-picker-left">Kalender</div>
            <div class="date-picker-right">
                <div id="datePickerOutlet"></div>
            </div>
        </div>
    </div>
</div>