<div class="<?php echo $this->wrapper_class ?>" data-on-document-ready="<?php echo $this->wrapper_class ?>_focusEffect<?php echo ($this->required ? ',' . $this->wrapper_class . '_required' : '') ?>">
    <input class="<?php echo $this->class ?>" type="text"  value="<?php echo $this->value; ?>" placeholder="<?php echo property_exists($this, 'placeholder') ? $this->placeholder : "" ?>" name="<?php echo $this->name ?>" <?php echo $this->customAttr ?>>
    <label class="active">
        <?php foreach ($this->getElements() as $obj) { ?>
            <?php echo $obj->getHtml(); ?>
        <?php } ?>
        <?php echo ($this->required == true ? ' *' : '') ?>
    </label>
</div>
