<div class="<?php echo $this->wrapper_class ?>" data-on-document-ready=" <?php echo $this->wrapper_class ?>_focusEffect, <?php echo ($this->required ? $this->wrapper_class . '_required,' : '') ?><?php echo $this->wrapper_class ?>_autosize">
    <textarea 
        class="<?php echo $this->class ?>" 
        placeholder="<?php echo $this->placeholder ?>" 
        name="<?php echo $this->name ?>" 
        <?php echo $this->customAttr ?> 
        ><?php echo $this->value; ?>
    </textarea>
    <label class="active"><?php echo $this->label ?><?php echo ($this->required == true ? ' *' : '') ?></label>
</div>