<div class="page-overlay">
    <div id="timePickerWrapper" class="<?= $this->class ?>"  <?= $this->customAttr ?>
         data-on-document-changed="initTimeInputEvent">
        <div class="time-picker-wrapper">
            <div class="time-picker-left">Uhrzeit</div>
            <div class="time-picker-right">
                <div id="timePickerOutlet"></div>
            </div>
        </div>
    </div>
</div>