<div 
    class="<?php echo $this->class ?>" 
    data-on-document-changed="template_tooltip_init"
    <?php echo $this->customAttr ?>><?php foreach ($this->getElements() as $obj) { ?><?php echo $obj->getHtml(); ?><?php } ?>
    <div class="tooltip">
        <div class="tooltip-content"><?php foreach ($this->tooltip as $obj) { ?>
                <?php echo $obj->getHtml(); ?>
            <?php } ?></div>
    </div>
</div>



